///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTeamCityTestToRun
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTeamCityTestToRunRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("a4d94fdc-1aca-4dba-afb9-3228651674c3")]
    public partial class MyTeamCityTestToRunRepository : RepoGenBaseFolder
    {
        static MyTeamCityTestToRunRepository instance = new MyTeamCityTestToRunRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTeamCityTestToRunRepository element repository.
        /// </summary>
        [RepositoryFolder("a4d94fdc-1aca-4dba-afb9-3228651674c3")]
        public static MyTeamCityTestToRunRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTeamCityTestToRunRepository() 
            : base("MyTeamCityTestToRunRepository", "/", null, 0, false, "a4d94fdc-1aca-4dba-afb9-3228651674c3", ".\\RepositoryImages\\MyTeamCityTestToRunRepositorya4d94fdc.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a4d94fdc-1aca-4dba-afb9-3228651674c3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class MyTeamCityTestToRunRepositoryFolders
    {
    }
#pragma warning restore 0436
}